name: "animals_image"

services:
  app:
    volumes:
      - .:/app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: "my_project"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: "my_db"
    environment:
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: "animals"
    volumes:
      - animals_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 10s

volumes:
  animals_data:
