# Generated by Django 4.2.18 on 2025-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'kitob ', 'verbose_name_plural': 'kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'janr ', 'verbose_name_plural': 'janrlar'},
        ),
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(default=50),
        ),
    ]
