ism = input("Ismingizni kiriting! ")
ism = ism.lower()
fam = input("Familyangizni kiriting! ")
fam = fam.lower()
joy = input("Yashash joyingizni kiriting! ")
joy = joy.lower()
print(f"Assalomu alaykum {ism} {fam}. Sizning yashash joyingiz {joy} da bolgani uchun bizni markazimizda 15% chegirma asosoida oqiy olasiz!")
