# Generated by Django 4.2.18 on 2025-02-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Hayvon ', 'verbose_name_plural': 'Hayvonlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tur ', 'verbose_name_plural': 'Turlar'},
        ),
    ]
