# Generated by Django 4.2 on 2024-12-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlati')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Davlati')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('year', models.IntegerField(verbose_name='Yili')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.brand', verbose_name='Brendi')),
            ],
        ),
    ]
