# Generated by Django 5.1.3 on 2025-01-17 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tur nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL atamasi')),
            ],
            options={
                'verbose_name': 'Tur ',
                'verbose_name_plural': 'Turlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Sarlavhasi')),
                ('text', models.TextField(max_length=2000, verbose_name='Matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('photo', models.ImageField(upload_to='news/images', verbose_name='Rasmi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yangilik muallifi')),
            ],
            options={
                'verbose_name': 'Yangilik ',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL atamasi')),
                ('description', models.TextField(blank=True, default="Ma'lumot qo'shilmagan!", max_length=1500, null=True, verbose_name='Haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('quantity', models.IntegerField(default=15, verbose_name='Miqdori')),
                ('weight', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('l', 'l'), ('ml', 'ml')], max_length=2, verbose_name="Og'irligi")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_shop.category', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Mahsulot ',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Izoh Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Izoh muallifi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.product', verbose_name='Mahsulot izohi')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images', verbose_name='Rasmi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.product', verbose_name='Mahsulot nomi')),
            ],
            options={
                'verbose_name': 'Rasm ',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
    ]
