# Generated by Django 5.1.3 on 2025-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_type',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('l', 'l'), ('ml', 'ml')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=4, verbose_name="Og'irligi"),
        ),
    ]
