# Generated by Django 5.1.3 on 2025-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_product_weight_type_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(max_length=4, verbose_name="Og'irligi"),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_type',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('l', 'l'), ('ml', 'ml')], default='kg', max_length=2, verbose_name="O'lchov birligi"),
        ),
    ]
