# Generated by Django 5.1.3 on 2025-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_alter_product_weight_alter_product_weight_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(verbose_name="Og'irligi"),
        ),
    ]
