# Generated by Django 5.1.3 on 2025-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_remove_product_quantity_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=15, verbose_name='Miqdori'),
        ),
    ]
